In [59]:
import pandas as pd 
import numpy as np
import datetime
import matplotlib.pyplot as plt 
from pandas.api.types import CategoricalDtype

In [60]:
austin_df= pd.read_csv('C:/Users/bharg/OneDrive/Documents/SPRING 2024/AIT 614/PROJECT/listings.csv')
austin_df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,3.291720e+05,"Hillside designer home,10 min.dwntn",1680871.0,Janet,NaN,78746.0,30.300850,-97.807940,Entire home/apt,495.0,3.0,7.0,8/7/2022,0.05,1.0,363.0,1.0,NaN
1,3.293060e+05,"Urban Homestead, 5 minutes to downtown",880571.0,Angel,NaN,78702.0,30.272320,-97.725790,Private room,63.0,2.0,570.0,11/30/2022,4.36,5.0,55.0,45.0,NaN
2,3.315490e+05,One Room with Private Bathroom,1690383.0,Sandra,NaN,78725.0,30.239110,-97.586250,Private room,100.0,2.0,0.0,NaN,NaN,1.0,0.0,0.0,NaN
3,3.338150e+05,Solar Sanctuary - Austin Room,372962.0,Kim,NaN,78704.0,30.253810,-97.752620,Private room,102.0,2.0,164.0,10/24/2022,1.26,1.0,36.0,18.0,NaN
4,3.334420e+05,Rare Secluded 1940s Estate,1698318.0,Virginia,NaN,78703.0,30.312670,-97.766410,Entire home/apt,286.0,3.0,163.0,11/12/2022,1.32,1.0,271.0,15.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13803,7.750000e+17,"Downtown Austin Pied de Terre, cute studio!",95139463.0,Felicity,NaN,78705.0,30.283945,-97.749639,Entire home/apt,56.0,30.0,0.0,NaN,NaN,15.0,365.0,0.0,NaN
13804,7.750000e+17,Bedroom W/ Shared Bathroom,286256623.0,Maris,NaN,78724.0,30.310313,-97.652324,Private room,34.0,30.0,0.0,NaN,NaN,4.0,168.0,0.0,NaN
13805,7.750000e+17,Creek Zen,490347286.0,Oleg,NaN,78723.0,30.319973,-97.676901,Private room,41.0,1.0,1.0,12/10/2022,1.00,1.0,276.0,1.0,NaN
13806,7.750000e+17,The Flamingo - 1/1 pink retreat,203862347.0,First,NaN,78751.0,30.303751,-97.716428,Entire home/apt,75.0,1.0,0.0,NaN,NaN,13.0,67.0,0.0,NaN
13807,7.750000e+17,Majic School Bus / Schoolie,23148741.0,Stewart,NaN,78704.0,30.258628,-97.784257,Entire home/apt,76.0,2.0,0.0,NaN,NaN,2.0,170.0,0.0,NaN

In [61]:
austin_df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,329172.0,"Hillside designer home,10 min.dwntn",1680871.0,Janet,NaN,78746.0,30.30085,-97.80794,Entire home/apt,495.0,3.0,7.0,8/7/2022,0.05,1.0,363.0,1.0,NaN
1,329306.0,"Urban Homestead, 5 minutes to downtown",880571.0,Angel,NaN,78702.0,30.27232,-97.72579,Private room,63.0,2.0,570.0,11/30/2022,4.36,5.0,55.0,45.0,NaN
2,331549.0,One Room with Private Bathroom,1690383.0,Sandra,NaN,78725.0,30.23911,-97.58625,Private room,100.0,2.0,0.0,NaN,NaN,1.0,0.0,0.0,NaN
3,333815.0,Solar Sanctuary - Austin Room,372962.0,Kim,NaN,78704.0,30.25381,-97.75262,Private room,102.0,2.0,164.0,10/24/2022,1.26,1.0,36.0,18.0,NaN
4,333442.0,Rare Secluded 1940s Estate,1698318.0,Virginia,NaN,78703.0,30.31267,-97.76641,Entire home/apt,286.0,3.0,163.0,11/12/2022,1.32,1.0,271.0,15.0,NaN

In [62]:
austin_df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
13803,7.750000e+17,"Downtown Austin Pied de Terre, cute studio!",95139463.0,Felicity,NaN,78705.0,30.283945,-97.749639,Entire home/apt,56.0,30.0,0.0,NaN,NaN,15.0,365.0,0.0,NaN
13804,7.750000e+17,Bedroom W/ Shared Bathroom,286256623.0,Maris,NaN,78724.0,30.310313,-97.652324,Private room,34.0,30.0,0.0,NaN,NaN,4.0,168.0,0.0,NaN
13805,7.750000e+17,Creek Zen,490347286.0,Oleg,NaN,78723.0,30.319973,-97.676901,Private room,41.0,1.0,1.0,12/10/2022,1.0,1.0,276.0,1.0,NaN
13806,7.750000e+17,The Flamingo - 1/1 pink retreat,203862347.0,First,NaN,78751.0,30.303751,-97.716428,Entire home/apt,75.0,1.0,0.0,NaN,NaN,13.0,67.0,0.0,NaN
13807,7.750000e+17,Majic School Bus / Schoolie,23148741.0,Stewart,NaN,78704.0,30.258628,-97.784257,Entire home/apt,76.0,2.0,0.0,NaN,NaN,2.0,170.0,0.0,NaN

In [63]:
#print the number of missing values for all the columns
print(austin_df.isna().sum())

id                                    3
name                                  3
host_id                               3
host_name                             5
neighbourhood_group               13808
neighbourhood                         3
latitude                              3
longitude                             3
room_type                             3
price                                 3
minimum_nights                        3
number_of_reviews                     3
last_review                        2863
reviews_per_month                  2863
calculated_host_listings_count        3
availability_365                      3
number_of_reviews_ltm                 3
license                           13808
dtype: int64

In [64]:
# Remove 'license' and 'neighbourhood_group' columns
df_cleaned = austin_df.drop(columns=['license', 'neighbourhood_group'])

# Now, you can check for missing values in the cleaned DataFrame
missing_values_cleaned = df_cleaned.isnull().sum()
print(missing_values_cleaned)

id                                   3
name                                 3
host_id                              3
host_name                            5
neighbourhood                        3
latitude                             3
longitude                            3
room_type                            3
price                                3
minimum_nights                       3
number_of_reviews                    3
last_review                       2863
reviews_per_month                 2863
calculated_host_listings_count       3
availability_365                     3
number_of_reviews_ltm                3
dtype: int64

In [65]:
##I defined the NOIR datatypes that is what columns are what datatype, using python and pandas 
# loop over the columns in the DataFrame and determine their NOIR data type
for col in austin_df.columns:
    dtype = str(austin_df[col].dtype)
    if CategoricalDtype.is_dtype(austin_df[col]):
        dtype = 'Nominal'
    elif austin_df[col].dtype == int:
        dtype = 'Ordinal' if austin_df[col].nunique() < 10 else 'Integer'
    elif austin_df[col].dtype == float:
        dtype = 'Ratio'
    print(col + ': ' + dtype)

id: Ratio
name: object
host_id: Ratio
host_name: object
neighbourhood_group: Ratio
neighbourhood: Ratio
latitude: Ratio
longitude: Ratio
room_type: object
price: Ratio
minimum_nights: Ratio
number_of_reviews: Ratio
last_review: object
reviews_per_month: Ratio
calculated_host_listings_count: Ratio
availability_365: Ratio
number_of_reviews_ltm: Ratio
license: Ratio

In [66]:
import pandas as pd

# Assuming df is your DataFrame 
# For example:
# df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Export DataFrame to CSV
df_cleaned.to_csv('C:/Users/bharg/OneDrive/Documents/SPRING 2024/AIT 614/PROJECT/finaldatacleaned.csv', index=False)